In [13]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.metrics import  silhouette_score, silhouette_samples
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [14]:
from sklearn.datasets import load_breast_cancer

In [15]:
cancer = load_breast_cancer()

In [33]:
from sklearn.datasets import load_breast_cancer
cancer = load_breast_cancer()
cancer.data.shape

(569, 30)

In [ ]:
# pca 2개의 주성분, ... 그이상 주성분 추출
# explained_variance_ratio_ 이 가장 높은 주성분의 갯수
# kmeans data=pca1, pca2, cluster=2

In [17]:
X = cancer.data

In [18]:
from sklearn.decomposition import PCA

# PCA 모델 a생성 - 주성분 2개
pca_1 = PCA(n_components=2)

# 모델 학습(규칙 설정)
pca_1.fit(X)

# 데이터 변환(PCA 적용)
X_pca = pca_1.transform(X)
X_pca[:2]
df_1 = pd.DataFrame(X_pca, columns=['ftr1', 'ftr2'])

In [19]:
pca_1.components_.shape

(2, 30)

In [34]:
df_1

ftr1        ftr2  kmeans_label
0    1160.142574 -293.917544             0
1    1269.122443   15.630182             0
2     995.793889   39.156743             0
3    -407.180803  -67.380320             1
4     930.341180  189.340742             0
..           ...         ...           ...
564  1414.126684  110.222492             0
565  1045.018854   77.057589             0
566   314.501756   47.553525             1
567  1124.858115   34.129225             0
568  -771.527622  -88.643106             1

[569 rows x 3 columns]

In [20]:
pca_1.explained_variance_ratio_

array([0.98204467, 0.01617649])

In [21]:
from sklearn.cluster import KMeans, DBSCAN
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

kmeans = KMeans(n_clusters=2, random_state=42)
kmeans_labels = kmeans.fit_predict(X_pca)

df_1['kmeans_label'] = kmeans_labels

print("KMeans Silhouette Score:", silhouette_score(X_pca, kmeans_labels))

KMeans Silhouette Score: 0.6984195775999954


c:\Users\Admin\miniconda3\envs\hi_ml_env\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(


# scaled data

In [22]:
scaler = StandardScaler()
scaler.fit(cancer.data)
X_scaled = scaler.transform(cancer.data)

PCA 1, PCA 2

In [23]:
from sklearn.decomposition import PCA

# PCA 모델 a생성 - 주성분 2개
pca_2 = PCA(n_components=2)

# 모델 학습(규칙 설정)
pca_2.fit(X_scaled)

# 데이터 변환(PCA 적용)
X_pca_2 = pca_2.transform(X_scaled)

In [24]:
pca_2.explained_variance_ratio_

array([0.44272026, 0.18971182])

In [25]:
pca_1.explained_variance_ratio_

array([0.98204467, 0.01617649])

In [26]:
# 주성분 갯수 5

In [27]:
import numpy as np

In [28]:
pca_3 = PCA(n_components=5)
pca_3.fit(X_scaled)
print(np.round(pca_3.explained_variance_ratio_, 3))
print(np.round(np.cumsum(pca_3.explained_variance_ratio_), 3))

[0.443 0.19  0.094 0.066 0.055]
[0.443 0.632 0.726 0.792 0.847]


In [29]:
pca_4 = PCA(n_components=7)
pca_4.fit(X_scaled)
print(np.round(pca_4.explained_variance_ratio_, 3))
print(np.round(np.cumsum(pca_4.explained_variance_ratio_), 3))

[0.443 0.19  0.094 0.066 0.055 0.04  0.023]
[0.443 0.632 0.726 0.792 0.847 0.888 0.91 ]


# 주성분 7개로 kmeans클러스터링

In [30]:
# 데이터 변환(PCA 적용)
X_pca_2 = pca_4.transform(X_scaled)
X_pca_2.shape


(569, 7)

In [31]:
df_2 = pd.DataFrame(X_pca_2, columns=['ftr1', 'ftr2',
                                      'ftr3', 'ftr4',
                                      'ftr5', 'ftr6',
                                      'ftr7'])
df_2[:3]

ftr1      ftr2      ftr3      ftr4      ftr5      ftr6      ftr7
0  9.192837  1.948583 -1.123166  3.633731 -1.195110  1.411424  2.159368
1  2.387802 -3.768172 -0.529293  1.118264  0.621775  0.028656  0.013359
2  5.733896 -1.075174 -0.551748  0.912083 -0.177086  0.541452 -0.668167

In [32]:
kmeans_2 = KMeans(n_clusters=2, random_state=42)
kmeans_2_labels = kmeans_2.fit_predict(X_pca_2)

df_2['kmeans_label'] = kmeans_2_labels

print("KMeans Silhouette Score:", silhouette_score(X_pca_2, kmeans_2_labels))

KMeans Silhouette Score: 0.3708218892715253


c:\Users\Admin\miniconda3\envs\hi_ml_env\lib\site-packages\sklearn\cluster\_kmeans.py:1446: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=3.
  warnings.warn(
